DROP TABLE IF EXISTS CLIENTES;

CREATE TABLE IF NOT EXISTS CLIENTES(
    id INT AUTO_INCREMENT NOT NULL,
    nome VARCHAR(30) NOT NULL,
    saldo DOUBLE,

    PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS CORRETORAS(
    id INT AUTO_INCREMENT NOT NULL,
    nome VARCHAR(30) NOT NULL,
    extrato DOUBLE,

    PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS HISTORICOS(
    id INT AUTO_INCREMENT NOT NULL,
    valorInvestido DOUBLE NOT NULL,
	dataRealizada DATE NOT NULL,

	PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS INVESTIMENTOS(
    id INT AUTO_INCREMENT NOT NULL,
	nome VARCHAR(30) NOT NULL,
	clienteId INT NOT NULL,
	corretoraId INT NOT NULL,

	PRIMARY KEY(id),
	FOREIGN KEY(clienteId) REFERENCES CLIENTES(id),
	FOREIGN KEY(corretoraId) REFERENCES CORRETORAS(id)
);

INSERT INTO CLIENTES(nome) VALUES
('Paulo'),
('Renato'),
('Victor'),
('Igor');

INSERT INTO CORRETORAS(nome) VALUES
('CORRETORA A'),
('CORRETORA B'),
('CORRETORA C');

INSERT INTO HISTORICOS(valorInvestido, dataRealizada) VALUES
(2000.0, TO_DATE('11-02-2020', 'd-m-Y')),
(1520.0, TO_DATE('21-06-2020', 'd-m-Y')),
(20.6, TO_DATE('01-03-2020', 'd-m-Y')),
(100.0, TO_DATE('31-06-2020', 'd-m-Y'));

INSERT INTO INVESTIMENTOS(nome, clienteId, corretoraId) VALUES
('INVESTIMENTO A', 1, 1),
('INVESTIMENTO B', 2, 1),
('INVESTIMENTO C', 1, 2),
('INVESTIMENTO D', 2, 2);